import { MigrationInterface, Repository } from 'typeorm';
import r365Datasource from '../datasource';
import { Resto365Area } from '@modules/resto365-area/entities/resto365-area.entity';
export class AddArea1715561180702 implements MigrationInterface {
  name = 'AddArea1715561180702';
  repo: Repository<Resto365Area>;
  constructor() {
    this.repo = r365Datasource.getRepository(Resto365Area);
  }
  public async up(): Promise<void> {
    const areas = [
      { name: 'New South Wales', countryId: 1, shortName: 'NSW' },
      { name: 'Queensland', countryId: 1, shortName: 'QLD' },
      { name: 'South Australia', countryId: 1, shortName: 'SA' },
      { name: 'Tasmania', countryId: 1, shortName: 'TAS' },
      { name: 'Victoria', countryId: 1, shortName: 'VIC' },
      { name: 'Western Australia', countryId: 1, shortName: 'WA' },
      { name: 'Australian Capital Territory', countryId: 1, shortName: 'ACT' },
      { name: 'Northern Territory', countryId: 1, shortName: 'NT' },
      { name: 'Alabama', countryId: 2, shortName: 'AL' },
      { name: 'Alaska', countryId: 2, shortName: 'AK' },
      { name: 'Arizona', countryId: 2, shortName: 'AZ' },
      { name: 'Arkansas', countryId: 2, shortName: 'AR' },
      { name: 'California', countryId: 2, shortName: 'CA' },
      { name: 'Colorado', countryId: 2, shortName: 'CO' },
      { name: 'Connecticut', countryId: 2, shortName: 'CT' },
      { name: 'Delaware', countryId: 2, shortName: 'DE' },
      { name: 'Florida', countryId: 2, shortName: 'FL' },
      { name: 'Georgia', countryId: 2, shortName: 'GA' },
      { name: 'Hawaii', countryId: 2, shortName: 'HI' },
      { name: 'Idaho', countryId: 2, shortName: 'ID' },
      { name: 'Illinois', countryId: 2, shortName: 'IL' },
      { name: 'Indiana', countryId: 2, shortName: 'IN' },
      { name: 'Iowa', countryId: 2, shortName: 'IA' },
      { name: 'Kansas', countryId: 2, shortName: 'KS' },
      { name: 'Kentucky', countryId: 2, shortName: 'KY' },
      { name: 'Louisiana', countryId: 2, shortName: 'LA' },
      { name: 'Maine', countryId: 2, shortName: 'ME' },
      { name: 'Maryland', countryId: 2, shortName: 'MD' },
      { name: 'Massachusetts', countryId: 2, shortName: 'MA' },
      { name: 'Michigan', countryId: 2, shortName: 'MI' },
      { name: 'Minnesota', countryId: 2, shortName: 'MN' },
      { name: 'Mississippi', countryId: 2, shortName: 'MS' },
      { name: 'Missouri', countryId: 2, shortName: 'MO' },
      { name: 'Montana', countryId: 2, shortName: 'MT' },
      { name: 'Nebraska', countryId: 2, shortName: 'NE' },
      { name: 'Nevada', countryId: 2, shortName: 'NV' },
      { name: 'New Hampshire', countryId: 2, shortName: 'NH' },
      { name: 'New Jersey', countryId: 2, shortName: 'NJ' },
      { name: 'New Mexico', countryId: 2, shortName: 'NM' },
      { name: 'New York', countryId: 2, shortName: 'NY' },
      { name: 'North Carolina', countryId: 2, shortName: 'NC' },
      { name: 'North Dakota', countryId: 2, shortName: 'ND' },
      { name: 'Ohio', countryId: 2, shortName: 'OH' },
      { name: 'Oklahoma', countryId: 2, shortName: 'OK' },
      { name: 'Oregon', countryId: 2, shortName: 'OR' },
      { name: 'Pennsylvania', countryId: 2, shortName: 'PA' },
      { name: 'Rhode Island', countryId: 2, shortName: 'RI' },
      { name: 'South Carolina', countryId: 2, shortName: 'SC' },
      { name: 'South Dakota', countryId: 2, shortName: 'SD' },
      { name: 'Tennessee', countryId: 2, shortName: 'TN' },
      { name: 'Texas', countryId: 2, shortName: 'TX' },
      { name: 'Utah', countryId: 2, shortName: 'UT' },
      { name: 'Vermont', countryId: 2, shortName: 'VT' },
      { name: 'Virginia', countryId: 2, shortName: 'VA' },
      { name: 'Washington', countryId: 2, shortName: 'WA' },
      { name: 'West Virginia', countryId: 2, shortName: 'WV' },
      { name: 'Wisconsin', countryId: 2, shortName: 'WI' },
    ];

    for (const [index, area] of areas.entries()) {
      await this.repo.save({
        id: index + 1,
        name: area.name,
        countryId: area.countryId,
        shortName: area.shortName,
        createdBy: 1,
        createdAt: new Date(),
        updatedby: 1,
        updatedAt: new Date(),
        version: 1,
      });
    }
  }

  public async down(): Promise<void> {
    const areaNames = [
      'New South Wales',
      'Queensland',
      'South Australia',
      'Tasmania',
      'Victoria',
      'Western Australia',
      'Australian Capital Territory',
      'Northern Territory',
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
    ];

    await this.repo.delete(areaNames);
  }
}
